# Generated by Django 6.0.2 on 2026-03-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('training', 'Обучение'), ('constructor', 'Конструктор'), ('furniture', 'Мебель')], max_length=20)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('is_hot', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('closed', 'Закрыт')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
